### ISSUE TITLE
给 idea2app 官网设计并配置动画

### ISSUE THREAD

**Issue by Soecka** [idea2app/idea2app.github.io#61]
### Task description

- [ ] [React bits](https://reactbits.dev/) Shadcn 动画组件库
- [ ] [viewTransition](https://developer.mozilla.org/zh-CN/docs/Web/API/ViewTransition)
- [ ] 搭配 [Speculation Rules API](https://developer.mozilla.org/en-US/docs/Web/API/Speculation_Rules_API)，参考网站 https://nerdy.dev/

### Reward currency

TQT $

### Reward amount

180

### Reward payer

石垚 <tech-query@idea2app.cn>

### Task source

https://idea2app.feishu.cn/record/NsiRrZPFLeHvHtcdfd5cFoOsnWc
